server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url:  jdbc:mysql:///leyou
    username: root
    password: 12345678
    hikari:
    # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 28830000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 9
  rabbitmq:
    host: 192.168.26.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
    #缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      exchange: LEYOU.ITEM.EXCHANGE
      #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
  instance:
  # 5秒钟发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 15秒不发送就过期
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo